### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by mose-s** [Flashs/virtualvideo#1]
Hi,
I've tried to run `showFish.py` example on Jetson Nano, but I got the following error:
```Traceback (most recent call last):
  File "showFish.py", line 30, in <module>
    fvd.run()
  File "/usr/local/lib/python3.6/dist-packages/virtualvideo-0.1.5-py3.6.egg/virtualvideo/devices.py", line 137, in run
BrokenPipeError: [Errno 32] Broken pipe
```
I have both ffmpeg-python and v4l2loopback installed and I can run the following line and see the fish without any problem:
`ffmpeg -loop 1 -re -i foo.jpg -f v4l2 -vcodec rawvideo -pix_fmt yuv420p /dev/video1`

Would you please help me fix this issue? Thanks!

**Comment by Flashs** [comment]
Hey, 
sorry for the late reply, but sure I'll have a look into it. 

To give you a heads up: I used this project on a Jetson Nano too, so I'm confident that we can resolve this problem.

**Comment by Flashs** [comment]
I ran into the same error really fast, due to not having the following documented:

The issue is that the `showFish.py` selects a different video_nr than you used to create the loopback device.  You can either change the first parameter of the `fvd.init_output ` line  in `showFish.py` or change the video_number of the loopback device. I uploaded another version that makes this clear in the Readme and also in the `showFish.py` example file. 

I hope this will help! If you have any further questions, let me know.

**Comment by mose-s** [comment]
It works perfectly now! I should have noticed that line... Thank you for your help!
